// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1:any,arg2:boolean):Promise<void>;

export function Fetch(arg1:string):Promise<any>;
