// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {setting} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Theme():Promise<setting.Themes>;
