// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteData(arg1) {
  return window['go']['main']['App']['DeleteData'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteTempfile(arg1) {
  return window['go']['main']['App']['DeleteTempfile'](arg1);
}

export function Download(arg1, arg2) {
  return window['go']['main']['App']['Download'](arg1, arg2);
}

export function Fetch(arg1) {
  return window['go']['main']['App']['Fetch'](arg1);
}

export function InitData() {
  return window['go']['main']['App']['InitData']();
}

export function InitSetting() {
  return window['go']['main']['App']['InitSetting']();
}

export function Set(arg1, arg2) {
  return window['go']['main']['App']['Set'](arg1, arg2);
}

export function Theme() {
  return window['go']['main']['App']['Theme']();
}
