// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1, arg2) {
  return window['go']['main']['App']['Download'](arg1, arg2);
}

export function Fetch(arg1) {
  return window['go']['main']['App']['Fetch'](arg1);
}
