// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}

export function Fetch(arg1) {
  return window['go']['main']['App']['Fetch'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitData() {
  return window['go']['main']['App']['InitData']();
}

export function Theme() {
  return window['go']['main']['App']['Theme']();
}
