// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultSetting() {
  return window['go']['store']['fileStore']['DefaultSetting']();
}

export function DeleteFile(arg1) {
  return window['go']['store']['fileStore']['DeleteFile'](arg1);
}

export function DeleteTempfile(arg1) {
  return window['go']['store']['fileStore']['DeleteTempfile'](arg1);
}

export function GetAllData() {
  return window['go']['store']['fileStore']['GetAllData']();
}

export function GetSetting() {
  return window['go']['store']['fileStore']['GetSetting']();
}

export function UpdateAllData(arg1) {
  return window['go']['store']['fileStore']['UpdateAllData'](arg1);
}

export function UpdateSetting(arg1) {
  return window['go']['store']['fileStore']['UpdateSetting'](arg1);
}
