// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {download} from '../models';

export function DeleteFile(arg1:download.Download):Promise<void>;

export function DeleteTempfile(arg1:download.Download):Promise<void>;

export function GetAllData():Promise<download.Lists>;

export function GetSetting():Promise<any>;

export function UpdateAllData(arg1:download.Lists):Promise<void>;

export function UpdateSetting(arg1:any):Promise<void>;
